name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      # Publish the site
      - name: Publish
        run: |
            cp TimeKeeper/wwwroot/index.html TimeKeeper/wwwroot/404.html
            dotnet publish TimeKeeper/TimeKeeper.csproj -c Release -o Prerender/output --nologo
            
     # Use NodeJS react-snap utility to prerender static website
      #- name: Prerender Blazor Client
      # working-directory: Prerender
      # run: npx react-snap
    
    # remove script tags after prerender
     # - name: Remove Script Tags
     #  working-directory: Prerender/output/wwwroot
     #   run: |
     #    find . -name "*.html" | while read htmlFile; do
     #       sed -i 's/<script>var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;<\/script><script src="_framework\/dotnet.6.0.1.jumy5461sl.js" defer="" integrity="sha256-awQsJ\/WxYhouHPuE+i3eJqjA4XClQlr2rD6nKvW80ww=" crossorigin="anonymous"><\/script>//g' $htmlFile
     #    done
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch Prerender/output/wwwroot/.nojekyll

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: public/wwwroot
          publish_dir: Prerender/output/wwwroot
          force_orphan: true
          keep_files: false
          # TODO uncomment the following line if you have a custom domain name
          cname: timekeeper.nielsen.tech
